/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {

        Carro fusca = new Carro();
        Carro ferrari = new Carro();

        fusca.definiCor("azul");
        IO.println(fusca.obterCor());
        IO.println(ferrari.obterCor());

        fusca.acelerar(10);
        IO.println(fusca.mostrarVelocidade());
        fusca.acelerar(100);
        IO.println(fusca.mostrarVelocidade());

    }
}
