/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

    Horario relogio = new Horario(100, 30, 20);

    IO.println(relogio.toString());



    }
}
