/*
 * This source file was generated by the Gradle 'init' task
 */
package engetelecom.poo;

public class App {
    static void main(String[] args) {

        Personagem heroi = new Personagem();

        heroi.preencherAtributos();

        IO.println();
        IO.println("Personagem criado!\n");

        IO.println("Status:");
        IO.println("Vida: " + heroi.informaVida());
        IO.println("Força: " + heroi.informaForca());
        IO.println("Agilidade: " + heroi.informaAgilidade());

        heroi.subirNivel();
        IO.println();
        IO.println("Subiu de nivel!!!");
        IO.println();
        IO.println("Status:");
        IO.println("Vida: " + heroi.informaVida());
        IO.println("Força: " + heroi.informaForca());
        IO.println("Agilidade: " + heroi.informaAgilidade());
        IO.println();
        IO.println("Levantou um objeto muitoo pesado!!!");
        IO.println();
        heroi.uparforca(20);

        IO.println("Força aumentou!!\n Força = " + heroi.informaForca());
        IO.println();
        IO.println("Bebeu uma poção de cura!!!");
        IO.println();
        heroi.uparVida(20);

        IO.println("Vida aumentou!!\n Vida = " + heroi.informaVida());
        IO.println();
        IO.println("Apostou uma corrida!!!");

        heroi.uparAgilidde(20);
        IO.println();
        IO.println("Agilidade aumentou!!\n Agilidade = " + heroi.informaAgilidade());


    }
}
