/*
 * This source file was generated by the Gradle 'init' task
 */
package engetelecom.poo;

public class App {

    public static void main(String[] args) {

        IO.println();
        
        Contador contagem = new Contador();

        contagem.incrementar();
        IO.println(contagem.mostrarContagem());

        for (int i = 0; i < 10; i++) {
            contagem.incrementar();
        }

        IO.println(contagem.mostrarContagem());

        contagem.alterarValor(100);
        IO.println(contagem.mostrarContagem());

    }
}
