/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.engtelecom;

public class App {
    public static void main(String[] args) {

       Motor v8 = new Motor(500,  8);
        Carro fusca = new Carro( v8, "Volkswagen");



    }
}
