/*
 * This source file was generated by the Gradle 'init' task
 */
package engetelecom.poo;

public class App {


    public static void main(String[] args) {

        String mes = IO.readln("Entre com o mês: ");
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));

//        String resultado = switch (mes.toLowerCase()){
//
//            case "janeiro","fevereiro"," -> return "Verão";
//
//
//        }




    }
}
