/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {

    HashMap<String, Livro> estante = new HashMap<>();

    public void cadastrar() {


        String isbn = IO.readln("Entre com o ISBN: ");
        if (!estante.containsKey(isbn)) {
            String nome = IO.readln("Entre com o nome do livro: ");
            String autor = IO.readln("Entre com o nome do autor: ");
            int ano = Integer.parseInt(IO.readln("Entre com o ano de publicação: "));
            Livro novo = new Livro(isbn, nome, autor, ano);
            this.estante.put(isbn, novo);
        } else {
            IO.println("ISBN já cadastrado!");
        }
    }

    public void listarCadastrados() {

        estante.forEach((isbn, nome) -> {
            IO.print("ISBN: " + isbn);
            IO.print(" |   Título: " + nome.getTitulo());
            IO.print("\n");
        });
    }

    public void consultarLivroIsbn() {
        String isbn = IO.readln("Entre com a ISBN do livro: ");
        Livro livro = estante.get(isbn);
        if (livro != null) {
            IO.print(livro);
        }
    }

    public void consultarLivroAutor() {
        String autor = IO.readln("Entre com a nome do autor: ");
        for (Livro livro : estante.values()) {
            if (livro.getAutor().equals(autor)) {

                IO.print("ISBN: " + livro.getIsbn());
                IO.print("  |  Título: " + livro.getTitulo());
            }
        }
    }

    public static void main(String[] args) {
        App app = new App();

//        app.cadastrar();
//        app.listarCadastrados();
//        app.consultarLivroIsbn();

        Livro l = new Livro("1234567890123", "titulo", "autor", 2026);

        IO.println(l);


    }


//    public void interface()
//
//    {
//
//        int escolha = 0;
//        switch (escolha) {
//            case 1:
//                break;
//            case 2:
//                break;
//            case 3:
//                break;
//            case 4:
//                break;
//            case 5:
//                break;
//            case 6:
//                break;
//            case 7:
//                break;
//            case 8:
//                break;
//            case 9:
//                break;
//            default:
//                IO.print("Escolha invalida!!");
//        }
//    }
}
