/*
 * This source file was generated by the Gradle 'init' task
 */
package engetelecom.poo;

public class App {

    public static void main(String[] args) {

        Batedeira batedeira = new Batedeira();

        batedeira.ligarDesligar();

        IO.println();
        if (batedeira.isLigado()) {
            IO.println("Batedeira ligada\n");
        } else {
            IO.println("Batedeira desligada\n");
        }

        // aumentar velocidade
        IO.println("Aumentar a velocidade");
        IO.println();
        for (int i = 0; i < 10; i++) {
            batedeira.alterarVelocidade(1);
            IO.println("Velocidade da batedeira: " + batedeira.informaVelocidade());
        }
        IO.println();

        // verifica ligado
        if (batedeira.isLigado()) {
            IO.println("Batedeira ligada\n");
        } else {
            IO.println("Batedeira desligada\n");

        }
        IO.println("Velocidade da batedeira: " + batedeira.informaVelocidade());

        // diminui velocidade
        IO.println();
        IO.println("Diminiur a velocidade\n");
        for (int i = 0; i < 10; i++) {
            batedeira.alterarVelocidade(-1);
            IO.println("Velocidade da batedeira: " + batedeira.informaVelocidade());
        }
        batedeira.ligarDesligar();
        IO.println();

        if (batedeira.isLigado()) {
            IO.println("Batedeira ligada\n");
        } else {
            IO.println("Batedeira desligada\n");
        }

    }
}
