/*
 * This source file was generated by the Gradle 'init' task
 */
package engetelecom.poo;

public class App {

    private Pessoa[] agenda = new Pessoa[100];
    private int contador = 0;

    private int menu() {

        IO.println("\n 1 - Cadastrar.");
        IO.println(" 2 - Buscar dados.");
        IO.println(" 3 - Listar usuarios.");
        IO.println(" 4 - Sair");

        return Integer.parseInt(IO.readln("\nEntre com a opção desejada: "));
    }

    private void cadastrar() {
        String nome = IO.readln("\nEntre com o nome do usuario: ");
        String email = IO.readln("Entre com o email do usuario: ");
        Pessoa cadastro = new Pessoa(nome, email);
        this.agenda[contador++] = cadastro;

    }


    public static void main(String[] args) {

        App app = new App();

        int escolha = 0;
        while (escolha != 4) {
            escolha = app.menu();
            switch (escolha) {

                case 1 -> {
                    app.cadastrar();
                }
                case 2 -> {
                    int tempID = Integer.parseInt(IO.readln("Digite o nome ID do usuario: "));
                    int i = 0;
                    while (app.agenda[i].getId() != tempID) {
                        i++;
                    }
                    IO.println("\n-------------------------------");
                    IO.println("Dados do usuario");
                    IO.println(app.agenda[i].toString());
                    IO.println("-------------------------------");
                }
                case 3 -> {
                    IO.println("Usuarios cadastrados: ");
                    IO.print("----------------------------------------------------------\n");
                    IO.println("|    ID     |      NOME      |           EMAIL           |");
                    IO.print("----------------------------------------------------------\n");
                    int i = 0;
                    while (app.agenda[i] != null) {

                        String s = String.format("|   %05d   |   %s    |     %s     |\n", app.agenda[i].getId(), app.agenda[i].getNome(), app.agenda[i].getEmail());
                        IO.print(s);
                        i++;
                    }

                }
            }
        }
    }
}

