/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;


import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<Pessoa> lista = new ArrayList<>();

        lista.add(new Pessoa("Pedro", "pedro@gmail.com"));
        lista.add(new Pessoa("Zequinha", "zequinha@gmail.com"));
        lista.add(new Pessoa("Juca", "juca@gmail.com"));
        lista.add(new Pessoa("Chico", "chico@gmail.com"));

        lista.forEach(IO::println);

        lista.removeIf(e -> e.getNome().equals("Juca"));

        lista.forEach(IO::println);






















//        ArrayList<String> lista = new ArrayList<>();
//
//        lista.add("Pessoa 1");
//        lista.add("Pessoa 2");
//
//
//        lista.size();
//
//        IO.println("FORI");
//
//        for (int i = 0; i < lista.size(); i++) {
//            IO.println(lista.get(i));
//        }
//        IO.println("FOR EACH");
//
//        for(String elemento: lista){
//            IO.println(elemento);
//        }
//
//        IO.println("FOR EACH (LAMBDA)");
//        lista.forEach(elemento -> IO.println(elemento));
//
//        lista.removeIf(e->e.equals("Pessoa 1"));

    }
}
