/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {


    public static void main(String[] args) {

        Caneta bic = new Caneta("azul", 100);

        bic.setNivelTinta(0.019282846855324668);
        IO.println("Nivel de tinta: " + bic.getNivelTinta());

        IO.println(bic.desenhar(0, 0 , 1, 0));

        IO.println("Nivel de tinta: " + bic.getNivelTinta());

    }
}
