/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import javax.imageio.metadata.IIOMetadataNode;

public class App {
    public static void main(String[] args) {

        disciplina poo = new disciplina();
        double notas[] = new double[3];
        int presenca;


        poo.preencherName(IO.readln("\nInsira o nome da matéria: "));

        for (int i = 0; i < 3; i++) {
            notas[i] = Double.parseDouble(IO.readln("Informe as notas da prova " + (i+1) + ": "));
        }

        poo.notas(notas);

        poo.preencherFaltas(presenca = Integer.parseInt(IO.readln("Insira a quantidade de faltas: ")));

        IO.println("O aluno foi: " + poo.passou() + " na materia " + poo.informaNome());
        IO.println("Média final: " + poo.mediaFinal());


    }
}
