/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.engtelecom;

public class App {
    public static void main(String[] args) {

    Aluno a1 = new Aluno("pedro", new Endereco("bananeira", "campinas", 92, 99101360),1123123123);

    IO.println(a1);

    }
}
