/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.engtelecom;

import net.datafaker.Faker;

public class App {
    public static void main(String[] args) {

        Faker faker = new Faker();
        String nome = faker.name().firstName();
        String rua = faker.address().streetAddress();
        String cep = faker.address().zipCode();

    Aluno a1 = new Aluno(nome, new Endereco(rua, "campinas", 92, cep),1123123123);

    IO.println(a1);

    }
}
