/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Data data = new Data(2022,2,21);

        IO.println(data.toString());

        IO.println(data.dataPorExtenso());


    }
}
