/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Aviao jato = new Aviao(1, 0, 100, 2, "turbina");

        IO.println("--- TESTE CRIAR JATO DESLIGADO --- ");
        IO.println(jato);

        IO.println("--- TESTE LIGAR JATO ---");
        jato.ligarDesligar();
        IO.println(jato);

        IO.println("--- TESTE DESLIGAR MOTOR 1 ---");
        jato.ligarDesligarMotor(0);
        IO.println(jato);

        IO.println("--- TESTE LIGAR MOTOR 2 E DESLIGAR MOTOR 1 ---");
        jato.ligarDesligarMotor(0);
        jato.ligarDesligarMotor(1);
        IO.println(jato);

        IO.println("--- TESTE DESLIGAR JATO ---");
        jato.ligarDesligar();
        IO.println(jato);


    }
}
