/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Ponto primeiro = new Ponto(0, 0);
        Ponto segundo = new Ponto(10, 10);

        IO.println("Coordenada X do primeiro ponto: " + primeiro.getX());
        IO.println("Coordenada Y do primeiro ponto: " + primeiro.getY());

        IO.println("Coordenada X do segundo ponto: " + segundo.getX());
        IO.println("Coordenada Y do segundo ponto: " + segundo.getY());

        IO.println("Distancia do segundo ponto do primeiro : " + segundo.distanciaPontos(primeiro));

        primeiro.setX(Integer.parseInt(IO.readln("Entre com as coordenadas alteradas de X para o primeiro ponto: ")));
        primeiro.setY(Integer.parseInt(IO.readln("Entre com as coordenadas alteradas de Y para o primeiro ponto: ")));

        IO.println("Nova distancia do segundo ponto do primeiro : " + segundo.distanciaPontos(primeiro));

        IO.println(primeiro.toString());
        IO.println(segundo.toString());
        
    }
}
